version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: loja-jogos-postgres
    environment:
      POSTGRES_DB: loja_jogos_tabuleiro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - loja-network
    restart: unless-stopped

  app:
    build: .
    container_name: loja-jogos-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/loja_jogos_tabuleiro
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8080:8080"
    networks:
      - loja-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  loja-network:
    driver: bridge

